#和.properties的区别是以层级结构书写配置信息
#取系统配置，如果没有取冒号后边的默认配置
#生产上我们可以加系统配置，这样我们在本地调试的时候可以直接取默认


spring:
  application:
    name: ${APP_NAME:unnamed}
  datasource:
    url: jdbc:hsqldb:file:testdb
    username: sa
    password:
    dirver-class-name: org.hsqldb.jdbc.JDBCDriver
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1

pebble:
  suffix:
  cache: false

server:
  port: ${APP_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include : info,health
#        include: info, health, beans, env, metrics

---
spring:
  profiles: test
server:
  port: 8000

---
spring:
  profiles: production
server:
  port: 80
pebble:
  cache: true

