#和.properties的区别是以层级结构书写配置信息
#取系统配置，如果没有取冒号后边的默认配置
#生产上我们可以加系统配置，这样我们在本地调试的时候可以直接取默认


spring:
  application:
    name: ${APP_NAME:unnamed}
  #Spring Boot就会自动创建出DataSource、JdbcTemplate、DataSourceTransactionManager，非常方便
  #禁用自动配置，因为这里有主从两个数据库，需要自己配置bean，这里模拟一下
  datasource-master:
    url: jdbc:hsqldb:file:testdb
    username: sa
    password:
    dirver-class-name: org.hsqldb.jdbc.JDBCDriver
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  datasource-slave:
    url: jdbc:hsqldb:file:testdb
    # 可替换为只有SELECT权限的只读用户:
    username: sa
    password:
    dirver-class-name: org.hsqldb.jdbc.JDBCDriver
    # HikariCP配置:
    hikari:
      auto-commit: false
      connection-timeout: 3000
      validation-timeout: 3000
      max-lifetime: 60000
      maximum-pool-size: 20
      minimum-idle: 1
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    ssl: ${REDIS_SSL:false}
    database: ${REDIS_DATABASE:0}
  artemis:
    # 指定连接外部Artemis服务器，而不是启动嵌入式服务:
    mode: native
    # 服务器地址和端口号:
    host: 127.0.0.1
    port: 61616
    # 连接用户名和口令由创建Artemis服务器时指定:
    user: admin
    password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # Kafka配置:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      auto-offset-reset: latest
      max-poll-records: 100
      max-partition-fetch-bytes: 1000000

pebble:
  suffix:
  cache: false

server:
  #实际监听接口
  port: ${APP_PORT:8080}
  #如果有反向代理读取客户端的http header，适配easyApi
  forward-headers-strategy: native


management:
  endpoints:
    web:
      exposure:
        include : info,health
#        include: info, health, beans, env, metrics

storage:
  type: ${STORAGE_TYPE:local}
  local:
    root-dir: ${STORAGE_LOCAL_ROOT:/var/storage}
    # max file size defaults to 100K:
    max-size: ${STORAGE_LOCAL_MAX_SIZE:102400}
    # allow empty file?
    allow-empty: false
    # allow types:
    allow-types: jpg, png, gif

---
spring:
  profiles: test
server:
  port: 8000

---
spring:
  profiles: production
server:
  port: 80
pebble:
  cache: true

